# Generated by Django 3.2.25 on 2024-10-11 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0004_auto_20241011_0224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Employees',
        ),
    ]
