# Generated by Django 3.2.25 on 2024-10-11 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0005_auto_20241011_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='emp_id',
        ),
    ]
